version: '3.4'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./traefik:/etc/traefik
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

  mariadb:
    image: mariadb
    container_name: mariadb
    restart: unless-stopped
    env_file:
      - .env.mariadb
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - mariadb_data:/var/lib/mysql

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - mongo_data:/data/db

  app:
    depends_on:
      - mongodb
      - mariadb
    image: primebot_backend-app:latest
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.rule=Host(`api.robinmoerlin.de`)"
      - "traefik.http.services.app.loadbalancer.server.port=8000"    
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=staging" 
  
  queue-cluster:
    depends_on:
      - mongodb
      - mariadb
    image: primebot_backend-queue-cluster:latest 
    env_file:
      - .env

  discord-bot:
    depends_on:
      - mariadb
      - mongodb
    image: primebot_backend-discord-bot:latest
    env_file:
      - .env

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    labels: 
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.rule=Host(`portainer.robinmoerlin.de`)"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=staging"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      
volumes:
  mariadb_data:
  mongo_data:
  portainer_data:
