global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

#api:
#  dashboard: true
#  insecure: true  # (optional) expose the dashboard! don't use in production!

# log:
#   level: DEBUG  # (Default: ERROR) Set the minimum log level. Accepted values: "DEBUG", "INFO", "WARN", "ERROR", "FATAL", "PANIC"

certificatesResolvers:
  staging:
    acme:
      email: robin.kehl@singular-it.de
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

  production:
    acme:
      email: robin.kehl@singular-it.de
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

providers:
  docker:
    exposedByDefault: false  # Default is true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
